vraag1/config/routes.rb
Rails.application.routes.draw do
  resources :todos
  get 'todos/new/:id', to: 'todos#new'
  post 'todos/new/:id', to: 'todos#new'
  
  root 'todos#new'

end

vraag1/app/models/todo.rb
class Todo < ActiveRecord::Base
end

vraag1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

vraag1/app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
      @db = CouchRest.database(ENV['DB'])
      @json_text = {'beginDate' => '20/01/2016', 'endDate' => '25/01/2016', 'priority' => '3', 'description' => 'Walk my dog', 'status' => 'not completed'}
	    @response = @db.save_doc(@json_text)    
	    @todo = Todo.new(beginDate: @json_text['beginDate'], endDate: @json_text['endDate'], priority: @json_text['priority'].to_i, description: @json_text['description'], status: @json_text['status'])
      if @todo.save
        @message = "sqlite3 data successfully inserted."
      end
      @todo_all = []
      @id_to_view = params[:id]
      @result = @db.view('_design/todo/_view/todo_all')['rows']
      @result.each do |todo|
        #puts "@@@@@@@@@@@@@@@@@@@éé = #{params[:id]} = #{todo['value']['priority']}"
        if params.has_key?(:id) then
          if (params[:id] == todo['value']['priority'])
            @todo_all.push(todo['value'])
          end
        else
          @todo_all.push(todo['value'])
        end
      end
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:beginDate, :endDate, :priority, :description, :status)
    end
end

vraag1/app/helpers/application_helper.rb
module ApplicationHelper
end

vraag1/app/helpers/todo_helper.rb
module TodoHelper
end

vraag1/app/helpers/todos_helper.rb
module TodosHelper
end

vraag1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vraag1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

vraag1/app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :beginDate %><br>
    <%= f.text_field :beginDate %>
  </div>
  <div class="field">
    <%= f.label :endDate %><br>
    <%= f.text_field :endDate %>
  </div>
  <div class="field">
    <%= f.label :priority %><br>
    <%= f.number_field :priority %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.number_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

vraag1/app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

vraag1/app/views/todos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Todos</h1>

<table>
  <thead>
    <tr>
      <th>Begindate</th>
      <th>Enddate</th>
      <th>Priority</th>
      <th>Description</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= todo.beginDate %></td>
        <td><%= todo.endDate %></td>
        <td><%= todo.priority %></td>
        <td><%= todo.description %></td>
        <td><%= todo.status %></td>
        <td><%= link_to 'Show', todo %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
        <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo', new_todo_path %>

vraag1/app/views/todos/new.html.erb
<h1> Welcome om te filteren  kan je bv dit doen : /todos/new/1 </h1>

<h3><%= @message %></h3>

<h3>Get ready for some json action!</h3>

<% if @id_to_view != nil %>
<h3>Je bent nu aan het filteren op priority : <%= @id_to_view %></h3>
<% end %>

<%= @todo_all %>

vraag1/app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Begindate:</strong>
  <%= @todo.beginDate %>
</p>

<p>
  <strong>Enddate:</strong>
  <%= @todo.endDate %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @todo.priority %>
</p>

<p>
  <strong>Description:</strong>
  <%= @todo.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @todo.status %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>